apiVersion: v1
kind: Pod
metadata:
  namespace: workspace02-st
  labels:
    run: workspace02
  name: workspace02
spec:
  containers:
  - image: atostrife/dbz:55
    name: workspace02

---

apiVersion: v1
kind: Service
metadata:
  namespace: workspace02-st
  labels:
    run: workspace02
  name: workspace02
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: workspace02

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workspace02-ingress-st
  namespace: workspace02-st
spec:
  ingressClassName: nginx
  rules:
  - host: workspace02-st.oecd.org
    http:
      paths:
      - backend:
          service:
            name: workspace02
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - workspace02.oecd.org
    secretName: oecd-wildcard-internal-tls
